INSERT INTO USER (ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME) VALUES (1, 'aaa', 'aaa', 'aaa', 'aaa');
INSERT INTO USER (ID, USERNAME, PASSWORD) VALUES (2, 'bbb', 'bbb');
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME) VALUES (3, 'ccc', 'ccc', 'ccc', 'ccc');
INSERT INTO USER (ID, USERNAME, PASSWORD) VALUES (4, 'ddd', 'ddd');
